server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#希望使用ip地址作为eureka的地址，并指定为127.0.0.1
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1